---
- name: "Neovim installation"
  hosts: localhost
  connection: local 
  gather_facts: false
  become: true
  tasks:
  - name: "Install Neovim and utils with pacman"
    community.general.pacman:
      state: "present"
      name:
        - luarocks  # lazy.nvim requirement
        - lua51  # lazy.nvim optional requirement => see `:checkhealth lazy` to get the version
        - lua
        - make  # needed by some plugins like telescope
        - pyright  # lsp
        - lua-language-server  # lsp
        - bash-language-server  # lsp
        - taplo-cli  # lsp toml
        - ripgrep  # telescope dependency
        - fd  # telescope dependency
        - stylua  # lua formatter
        - tree-sitter-cli  # treesitter dependency
        - neovim
